version: '{build}'

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    CMAKE_GENERATOR: "Visual Studio 15 2017"

build_script:
  - cmd: mkdir build && cd build
  - cmd: cmake .. -DABC_USE_NO_PTHREADS=ON -DABC_USE_NO_READLINE=ON -DCMAKE_INSTALL_PREFIX=%CD% -G "%CMAKE_GENERATOR%"
  - cmd: cmake --build . --target libabc --config Release -- -m
  - cmd: cmake --build . --target abc --config Release -- -m
  - cmd: cmake --build . --target install --config Release -- -m
  - cmd: ctest -VV -C Release
  - cmd: bin\abc -c "r %APPVEYOR_BUILD_FOLDER%/i10.aig; b; ps; b; rw -l; rw -lz; b; rw -lz; b; ps; cec"
  - cmd: appveyor PushArtifact bin/abc.exe
