version: '{build}'

environment:

  matrix:

  - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    VCVARS_SCRIPT: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"
    VCVARS_PLATFORM: x86

init:

  - cmd: '"%VCVARS_SCRIPT%" %VCVARS_PLATFORM%'

build_script:

  - cmd: |
      sed -i 's#ABC_USE_PTHREADS"#ABC_DONT_USE_PTHREADS" /D "_XKEYCHECK_H"#g' *.dsp
      awk 'BEGIN { del=0; } /# Begin Group "uap"/ { del=1; } /# End Group/ { if( del > 0 ) {del=0; next;} } del==0 {print;} ' abclib.dsp > tmp.dsp
      copy tmp.dsp abclib.dsp
      del tmp.dsp
      unix2dos *.dsp

  - cmd: |
      appveyor PushArtifact abcspace.dsw
      appveyor PushArtifact abclib.dsp
      appveyor PushArtifact abcexe.dsp

  - cmd: |
      devenv abcspace.dsw /upgrade || dir
      appveyor PushArtifact UpgradeLog.htm
      msbuild abcspace.sln /m /nologo /p:Configuration=Release

  - cmd: |
      _TEST\abc.exe -c "r i10.aig; b; ps; b; rw -l; rw -lz; b; rw -lz; b; ps; cec"

  - cmd: |
      appveyor PushArtifact _TEST/abc.exe

