language: cpp

matrix:
  include:

    - os: linux
      addons:
        apt:
          packages:
            - libreadline-dev

    - os: linux
      addons:
        apt:
          packages:
            - libreadline-dev
      env: 
        MAKE_ARGS: ABC_USE_NAMESPACE=xxx
        DEMO_ARGS: -DABC_NAMESPACE=xxx

    - os: osx
      osx_image: xcode8
      before_install:
        - brew update
        - brew install readline

script:
  
  - make ${MAKE_ARGS} -j2 abc
  - ./abc -c "r i10.aig; b; ps; b; rw -l; rw -lz; b; rw -lz; b; ps; cec"

  - make ${MAKE_ARGS} libabc.a
  - g++ ${DEMO_ARGS} -Wall -c src/demo.c -o demo.o
  - g++ -o demo demo.o libabc.a -lm -ldl -lreadline -lpthread
  - ./demo i10.aig
