SRC +=    src/aig/gia/giaAig.c \
    src/aig/gia/giaAgi.c \
    src/aig/gia/giaAiger.c \
    src/aig/gia/giaAigerExt.c \
    src/aig/gia/giaBalance.c \
    src/aig/gia/giaBidec.c \
    src/aig/gia/giaCCof.c \
    src/aig/gia/giaCex.c \
    src/aig/gia/giaCof.c \
    src/aig/gia/giaCone.c \
    src/aig/gia/giaCSatOld.c \
    src/aig/gia/giaCSat.c \
    src/aig/gia/giaCTas.c \
    src/aig/gia/giaDfs.c \
    src/aig/gia/giaDup.c \
    src/aig/gia/giaEmbed.c \
    src/aig/gia/giaEnable.c \
    src/aig/gia/giaEquiv.c \
    src/aig/gia/giaEra.c \
    src/aig/gia/giaEra2.c \
    src/aig/gia/giaFanout.c \
    src/aig/gia/giaForce.c \
    src/aig/gia/giaFrames.c \
    src/aig/gia/giaFront.c \
    src/aig/gia/giaFx.c \
    src/aig/gia/giaGlitch.c \
    src/aig/gia/giaHash.c \
    src/aig/gia/giaIf.c \
    src/aig/gia/giaIso.c \
    src/aig/gia/giaIso2.c \
    src/aig/gia/giaJf.c \
    src/aig/gia/giaMan.c \
    src/aig/gia/giaMem.c \
    src/aig/gia/giaMfs.c \
    src/aig/gia/giaMini.c \
    src/aig/gia/giaMuxes.c \
    src/aig/gia/giaPat.c \
    src/aig/gia/giaResub.c \
    src/aig/gia/giaRetime.c \
    src/aig/gia/giaScl.c \
    src/aig/gia/giaShrink.c \
    src/aig/gia/giaShrink6.c \
    src/aig/gia/giaShrink7.c \
    src/aig/gia/giaSim.c \
    src/aig/gia/giaSim2.c \
    src/aig/gia/giaSort.c \
    src/aig/gia/giaSpeedup.c \
    src/aig/gia/giaStg.c \
    src/aig/gia/giaSupMin.c \
    src/aig/gia/giaSweep.c \
    src/aig/gia/giaSweeper.c \
    src/aig/gia/giaSwitch.c \
    src/aig/gia/giaTim.c \
    src/aig/gia/giaTruth.c \
    src/aig/gia/giaTsim.c \
    src/aig/gia/giaUtil.c
