SRC +=    src/aig/gia/gia.c \
    src/aig/gia/giaAbs.c \
    src/aig/gia/giaAbsVta.c \
    src/aig/gia/giaAig.c \
    src/aig/gia/giaAiger.c \
    src/aig/gia/giaBidec.c \
    src/aig/gia/giaCCof.c \
    src/aig/gia/giaCof.c \
    src/aig/gia/giaCSatOld.c \
    src/aig/gia/giaCSat.c \
    src/aig/gia/giaCTas.c \
    src/aig/gia/giaDfs.c \
    src/aig/gia/giaDup.c \
    src/aig/gia/giaEmbed.c \
    src/aig/gia/giaEnable.c \
    src/aig/gia/giaEquiv.c \
    src/aig/gia/giaEra.c \
    src/aig/gia/giaEra2.c \
    src/aig/gia/giaFanout.c \
    src/aig/gia/giaForce.c \
    src/aig/gia/giaFrames.c \
    src/aig/gia/giaFront.c \
    src/aig/gia/giaGlitch.c \
    src/aig/gia/giaHash.c \
    src/aig/gia/giaIf.c \
    src/aig/gia/giaMan.c \
    src/aig/gia/giaMem.c \
    src/aig/gia/giaPat.c \
    src/aig/gia/giaReparam.c \
    src/aig/gia/giaRetime.c \
    src/aig/gia/giaScl.c \
    src/aig/gia/giaShrink.c \
    src/aig/gia/giaSim.c \
    src/aig/gia/giaSim2.c \
    src/aig/gia/giaSort.c \
    src/aig/gia/giaSpeedup.c \
    src/aig/gia/giaSupMin.c \
    src/aig/gia/giaSwitch.c \
    src/aig/gia/giaTsim.c \
    src/aig/gia/giaUtil.c
