SRC +=    src/aig/saig/saigAbs.c \
    src/aig/saig/saigAbsCba.c \
    src/aig/saig/saigAbsPba.c \
    src/aig/saig/saigAbsStart.c \
    src/aig/saig/saigAbsVfa.c \
    src/aig/saig/saigBmc.c \
    src/aig/saig/saigBmc2.c \
    src/aig/saig/saigBmc3.c \
    src/aig/saig/saigCexMin.c \
    src/aig/saig/saigCone.c \
    src/aig/saig/saigConstr.c \
    src/aig/saig/saigConstr2.c \
    src/aig/saig/saigDual.c \
    src/aig/saig/saigDup.c \
    src/aig/saig/saigGlaCba.c \
    src/aig/saig/saigGlaPba.c \
    src/aig/saig/saigGlaPba2.c \
    src/aig/saig/saigHaig.c \
    src/aig/saig/saigInd.c \
    src/aig/saig/saigIoa.c \
    src/aig/saig/saigMiter.c \
    src/aig/saig/saigOutDec.c \
    src/aig/saig/saigPhase.c \
    src/aig/saig/saigRefSat.c \
    src/aig/saig/saigRetFwd.c \
    src/aig/saig/saigRetMin.c \
    src/aig/saig/saigRetStep.c \
    src/aig/saig/saigScl.c \
    src/aig/saig/saigSimExt.c \
    src/aig/saig/saigSimExt2.c \
    src/aig/saig/saigSimFast.c \
    src/aig/saig/saigSimMv.c \
    src/aig/saig/saigSimSeq.c \
    src/aig/saig/saigStrSim.c \
    src/aig/saig/saigSwitch.c \
    src/aig/saig/saigSynch.c \
    src/aig/saig/saigTempor.c \
    src/aig/saig/saigTrans.c \
    src/aig/saig/saigWnd.c
